username: '17602222983'

password: 'loveME970803'

# 演唱会详情页面URL
ticket_url: 'https://detail.damai.cn/item.htm?spm=a2oeg.search_category.0.0.530d3f5aJjQxNP&id=768781092407&clicktitle=%E9%82%93%E7%B4%AB%E6%A3%8BI%20AM%20GLORIA%20%E5%B7%A1%E5%9B%9E%E6%BC%94%E5%94%B1%E4%BC%9A-%E5%A4%A9%E6%B4%A5%E7%AB%99'

# 购买哪个站点
ticket_site: "天津站"

# 场次日期
ticket_date: "2024-05-02"

# 票档
ticket_grade: "内场1399元"

# 购买数量
ticket_num: 2

# 实名人名字, 没有相同姓氏只写姓即可，否则写完整姓名. 实名人数量需要与购票数量一致
real_names:
  - 宋希彧 - 周鑫


